### PR TITLE
Test MS Test Friendly Test Names

### PR DESCRIPTION
**Pull request by spottedmahn**
image

### CODE REVIEW

**Comment by spottedmahn** [comment]
https://dotnet.myget.org/feed/mstestv2/package/nuget/MSTest.TestAdapter

image

image

take it's suggestion and use the `[ Nearest version: 2.1.0-beta ]`

image

Yeah, it worked! 🤩

----

So is myget.org "wrong"?  Why did their instructions say to use `2.1.0-build-20191217-01`?  Or it is b/c of how [microsoft/testfx](https://github.com/microsoft/testfx) is configured? 🤔

@nohwnd thoughts?

**Comment by nohwnd** [comment]
@spottedmahn running this works fine for me, so dunno.

`Install-Package MSTest.TestFramework -Version 2.1.0-build-20191217-01 -Source https://dotnet.myget.org/F/mstestv2/api/v3/index.json`

You can grab the latest beta2 from nuget.org as well btw.

**Comment by nohwnd** [comment]
@spottedmahn wait I see it, you are specifying the source, but it is not respected by the command as the warning suggests. I have the myget source in my nuget sources (set by the visual studio menu), but you probably don't so it only resolves from nuget.org and fails because the version is not there. That also explains why the closest version is -beta2, because on myget the closest version would be different. When I disable the myget source in the menu I can see the same error message as you.

**Comment by spottedmahn** [comment]
>as the warning suggests

🤦‍♂️, you mean I should [read the errors/warnings](https://github.com/spottedmahn/my-blog/issues/11#issue-348073274)?!  😜

Thanks @nohwnd!

**Pull request merged**
